#!/bin/bash

#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc core::plugin_dir ~/.chunkwm_plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 1

#
# NOTE: The following are config variables for the chunkwm-tiling plugin
#

chunkc set global_desktop_mode           bsp
chunkc set 2_desktop_mode                monocle
chunkc set 5_desktop_mode                float

chunkc set 1_desktop_tree                ~/.chunkwm_layouts/dev_1

chunkc set global_desktop_offset_top     20
chunkc set global_desktop_offset_bottom  20
chunkc set global_desktop_offset_left    20
chunkc set global_desktop_offset_right   20
chunkc set global_desktop_offset_gap     15

chunkc set 1_desktop_offset_top          190
chunkc set 1_desktop_offset_bottom       190
chunkc set 1_desktop_offset_left         190
chunkc set 1_desktop_offset_right        190
chunkc set 1_desktop_offset_gap          15

chunkc set 3_desktop_offset_top          190
chunkc set 3_desktop_offset_bottom       190
chunkc set 3_desktop_offset_left         190
chunkc set 3_desktop_offset_right        190

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           1
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

chunkc set preselect_border_color        0xffffff00
chunkc set preselect_border_width        4
chunkc set preselect_border_radius       4

# signal dock to make windows topmost when floated
# requires chwm-sa (https://github.com/koekeishiya/chwm-sa)
chunkc set window_float_topmost          0

#
# NOTE: The following are config variables for the chunkwm-border plugin
#

chunkc set focused_border_color          0xffc0b18b
chunkc set focused_border_width          4
chunkc set focused_border_radius         4
chunkc set focused_border_skip_floating  0

#
# NOTE: specify plugins to load when chunkwm starts.
#

chunkc core::load tiling.so
chunkc core::load ffm.so
chunkc core::load border.so

chunkc tiling::rule --owner \"System Preferences\" --state tile
chunkc tiling::rule --owner Finder --name Copy --state float

#
# NOTE: if chunkc plugin_dir is not set, the absolutepath is necessary.
#

# chunkc core::load ~/.chunkwm_plugins/tiling.so
# chunkc core::load ~/.chunkwm_plugins/ffm.so
# chunkc core::load ~/.chunkwm_plugins/border.so

