#!/bin/bash

#
# NOTE: specify the absolutepath of the file to use for logging.
#       'stdout' and 'stderr' are valid values.
#

# chunkc core::log_file ~/.chunkwm_log
chunkc core::log_file stdout

#
# NOTE: specify the desired level of logging.
#
#       - none, debug, warn, error
#

chunkc core::log_level debug

#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc core::plugin_dir ~/.chunkwm_plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 1

#
# NOTE: the following are config variables for the chunkwm-tiling plugin.
#

chunkc set global_desktop_mode           bsp
chunkc set 2_desktop_mode                monocle
chunkc set 5_desktop_mode                float

# chunkc set 1_desktop_tree                ~/.chunkwm_layouts/test_1

chunkc set global_desktop_offset_top     20
chunkc set global_desktop_offset_bottom  20
chunkc set global_desktop_offset_left    20
chunkc set global_desktop_offset_right   20
chunkc set global_desktop_offset_gap     20

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc set mouse_move_window             \"shift 1\"
chunkc set mouse_resize_window           \"ctrl shift 1\"
chunkc set mouse_motion_interval         35

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        5
chunkc set preselect_border_radius       0

#
# NOTE: these settings require chwm-sa.
#       (https://github.com/koekeishiya/chwm-sa)
#

chunkc set window_float_topmost          0
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.25
chunkc set window_use_cgs_move           0

#
# NOTE: the following are config variables for the chunkwm-border plugin.
#

chunkc set focused_border_color          0xff775759
chunkc set focused_border_width          5
chunkc set focused_border_radius         0
chunkc set focused_border_skip_floating  1
chunkc set focused_border_skip_monocle   1

#
# NOTE: the following are config variables for the chunkwm-ffm plugin.
#

chunkc set ffm_bypass_modifier           \"cmd shift\"

#
# NOTE: specify plugins to load when chunkwm starts.
#       if chunkc plugin_dir is not set, the absolutepath is necessary.
#

chunkc core::load border.so
chunkc core::load ffm.so
chunkc core::load purify.so
chunkc core::load tiling.so

#
# NOTE: sample rules for the tiling plugin
#

chunkc tiling::rule --owner mpv --state float &
chunkc tiling::rule --owner kitty --role AXWindow --subrole AXDialog --state tile &
chunkc tiling::rule --owner Finder --name Copy --state float &
chunkc tiling::rule --owner \"App Store\" --state float &
chunkc tiling::rule --owner Spotify --desktop 5 --follow-desktop &
chunkc tiling::rule --owner Steam --desktop 5 --follow-desktop &
chunkc tiling::rule --owner Discord --desktop 5 --follow-desktop &

dock-inject &
