set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'Shougo/deoplete.nvim'
Plugin 'critiqjo/lldb.nvim'
Plugin 'vim-airline/vim-airline'
Plugin 'bling/vim-bufferline'
Plugin 'morhetz/gruvbox'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

version 6.0
if &cp | set nocp | endif
let s:cpo_save=&cpo
set cpo&vim
inoremap jk <Esc>
nnoremap √ :m .+1<CR>==
nnoremap ª :m .-2<CR>==
inoremap √ <Esc>:m .+1<CR>==gi
inoremap ª <Esc>:m .-2<CR>==gi
vnoremap √ :m '>+1<CR>gv=gv
vnoremap ª :m '<-2<CR>gv=gv
nnoremap <F1> :cprev<cr>
nnoremap <F2> :cnext<cr>
nmap <F4> <Plug>LLBreakSwitch
nnoremap <F5> :LLmode debug<CR>
nnoremap <F6> :LL step<CR>
nnoremap <F7> :LL next<CR>
nnoremap <F8> :LL continue<CR>
nnoremap <F9> :LL process interrupt<CR>
nnoremap <F11> :silent make\|cwindow\|redraw!<cr>
nnoremap <F12> :silent make install\|cwindow\|redraw!<cr>

if has('nvim')
    tnoremap <Esc> <c-\><c-n>
endif

let mapleader = ','

let g:python_host_prog = '/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python'


"tab adds 4spaces
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

let g:deoplete#enable_at_startup = 1

let &cpo=s:cpo_save
unlet s:cpo_save
set backspace=2
set fileencodings=ucs-bom,utf-8,default,latin1
set encoding=utf-8
set modelines=0
set window=0
set number
set hidden
set nowrap
set hlsearch            " Highlight search results.
set ignorecase          " Make searching case insensitive
set smartcase           " ... unless the query has capital letters.
set incsearch
set switchbuf=usetab,newtab
set nojoinspaces
set cino==0             " disable retarded indentation after case labels
"set cursorline
"let loaded_matchparen=1 " Don't load matchit.vim (paren/bracket matching)
"set noshowmatch         " Don't match parentheses/brackets
set noshowcmd
set noshowmode
set nocursorline        " Don't paint cursor line
set nocursorcolumn      " Don't paint cursor column
set lazyredraw          " Wait to redraw
"set scrolljump=8       " Scroll 8 lines at a time at bottom/top
let html_no_rendering=1 " Don't render italic, bold, links in HTML
autocmd BufWritePre * :%s/\s\+$//e

set guitablabel=%N/\ %t\ %M

" vim: set ft=vim :

" enables to search in all open buffers with :Search <pattern>
function! BuffersList()
  let all = range(0, bufnr('$'))
  let res = []
  for b in all
    if buflisted(b)
      call add(res, bufname(b))
    endif
  endfor
  return res
endfunction

function! GrepBuffers (expression)
  exec 'vimgrep/'.a:expression.'/ '.join(BuffersList())
endfunction

command! -nargs=0 Cclear call setqflist([]) | cclose

command! -nargs=+ Search call setqflist([]) | call GrepBuffers(<q-args>) | copen

abbreviate cmain int main(int Count, char **Args)
            \<CR>{<CR>return EXIT_SUCCESS;<CR>}<UP><UP>

abbreviate cerror void Error(const char *Format, ...)
            \<CR>{<CR>va_list Args;<CR>va_start(Args, Format);
            \<CR>vfprintf(stderr, Format, Args);
            \<CR>va_end(Args);<CR>exit(EXIT_FAILURE);<CR>}

abbreviate cargs int ParseArguments(int Count, char **Args)
            \<CR>{<CR>int Option;<CR>const char *Short = "";
            \<CR>struct option Long[] =<CR>{<CR>{ NULL, 0, NULL, 0 }<CR>};<CR>
            \<CR>while((Option = getopt_long(Count, Args, Short, Long, NULL)) != -1)
            \<CR>{<CR>switch(Option)<CR>{<CR>}<CR>}<CR><CR>return 0;<CR>}

let macvim_skip_colorscheme=0
let g:airline_powerline_fonts=1
let g:airline_theme='gruvbox'
syntax enable
compiler gcc

colorscheme koe
